name: Release Build

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    concurrency:
      group: release-build-${{ inputs.tag || github.ref_name }}
      cancel-in-progress: true
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: Determine tag name
        id: tag
        run: |
          TAG="${{ inputs.tag }}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "Using tag: $TAG"

      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.tag.outputs.tag }}

      - name: Install ffmpeg (audio conversion)
        run: |
          apt-get update
          apt-get install -y ffmpeg

      # devkitpro/devkitarm image already includes the toolchain; install extra libs only if needed
      - name: Install 3DS dependencies (if needed)
        run: |
          true

      - name: Build (make)
        env:
          DEVKITPRO: /opt/devkitpro
          DEVKITARM: /opt/devkitpro/devkitARM
        run: |
          make -s

      - name: Archive artifact
        run: |
          mkdir -p artifacts
          cp -f Ballistica.3dsx artifacts/

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: artifacts/Ballistica.3dsx
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
