name: Release Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install ffmpeg (audio conversion)
        run: |
          apt-get update
          apt-get install -y ffmpeg

      # devkitpro/devkitarm image already includes the toolchain; install extra libs only if needed
      - name: Install 3DS dependencies (if needed)
        run: |
          true

      - name: Build (make)
        env:
          DEVKITPRO: /opt/devkitpro
          DEVKITARM: /opt/devkitpro/devkitARM
        run: |
          make -s

      - name: Archive artifact
        run: |
          mkdir -p artifacts
          cp -f Ballistica.3dsx artifacts/

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: artifacts/Ballistica.3dsx
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
